### ISSUE TITLE
EPS telemetry out of range?

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/EPS_FlightSoftware#15]
see https://github.com/DelfiSpace/OBC_FlightSoftware/issues/5

**Comment by CasperBroekhuizen** [comment]
bug in the Telemetry Generation file that I'm aware of, normally I fix it manually, it must've slipped by me...

Fixed in https://github.com/DelfiSpace/EPS_FlightSoftware/commit/8c9f247cd8069207c77b82f2c67827a007b84cb9
