### ISSUE TITLE
Gas gauge accuracy seems poor

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/EPS_FlightSoftware#8]

**Comment by MFvandenBos** [comment]
![image](https://user-images.githubusercontent.com/35063713/72060017-7162a580-32d3-11ea-9dfc-712ccf36162d.png)

**Comment by MFvandenBos** [comment]
Note the battery current in the picture of the previous comment

**Comment by MFvandenBos** [comment]
![image](https://user-images.githubusercontent.com/35063713/72060397-2b5a1180-32d4-11ea-8228-ebfacbf84364.png)


note how the gas gauge value has changed compared to the previous picture

**Comment by StefanoSperetta** [comment]
The current being negative means we are charging. It should not have been red though...

But what's the time difference between the two screenshots?
EPS sw revision? Current master EPS?

I think I removed the code in the gas gauge using the offset but purely outputting the charge accumulator directly...

**Comment by MFvandenBos** [comment]
Time difference is ~ 5 minutes, sw version is current master. It discharged from 4916 to 64817

**Comment by StefanoSperetta** [comment]
the problem is that the "offset" is still in the LTC2942 code. I tried to implement it correctly but we still have glitches in there...

What I can do is disable this offset but we will anyway see a jump when the charger stops the charging process (it is implemented in hardware). 

So, what will happen is that the battery will keep charging and when the voltage reaches 4.2V (on the protection switch), the charge will jump to 65535 and stay there till the battery voltage starts decreasing. But for the rest it should change linearly with charge/discharge...

**Comment by MFvandenBos** [comment]
solved by new LTC chips
