### ISSUE TITLE
NMI pin reset is never cleared

### ISSUE THREAD

**Issue by MFvandenBos** [DelfiSpace/EPS_FlightSoftware#9]
![image](https://user-images.githubusercontent.com/35063713/72887651-6d3f7a80-3d0c-11ea-89ff-326e51b33343.png)

As in the above image, this reset cause is not cleared, except by re-uploading code.  This can place the satellite in unrecoverable condition

**Comment by MFvandenBos** [comment]
![image](https://user-images.githubusercontent.com/35063713/72887932-e939c280-3d0c-11ea-9e4a-2757560d1abd.png)

**Comment by MFvandenBos** [comment]
Problem was caused by systick being too fast and the watchdog too slow. https://github.com/DelfiSpace/EPS/issues/24

**Comment by StefanoSperetta** [comment]
Cause identified, Issue needs to be fixed at hardware level.

**Comment by StefanoSperetta** [comment]
PeriodicTaskNotifier.cpp still needs to be fixed...

Use again TIMER32 might be a good temporary fix, but it would be best to link the fix of this issue to https://github.com/DelfiSpace/DelfiPQcore/issues/17

**Comment by CasperBroekhuizen** [comment]
Workaround for now with the TIMER32. As the SystickPeriod seems to be a 32bit value, but is actually a 24bit value (http://www.ti.com/lit/ug/slau356i/slau356i.pdf). Meaning that a 1 second period (48MCycles) is too big for this register. 

See commit: https://github.com/DelfiSpace/DelfiPQcore/commit/e352f39656140fab495fbd4a70bca4afcf1d6bd8

**Comment by StefanoSperetta** [comment]
Workaround implemented, fixing the issue will require quite some time. The issue for fixing this issue on DelfiPQCore is already in place, so closing this one...
